@jwt = 

POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "product_id": 2,
    "quantity": 1
}

###
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}

###
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "subtotal": 1,
    "tax": 0.09,
    "total": 1.09
    }