@jwt = 

POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "product_id": 2,
    "quantity": 1
}

###
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}

###
DELETE http://localhost:3000/carted_products/7.json
Authorization: Bearer {{jwt}}
