
@jwt = 

POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 3
}

###

GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

###

GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}